import React, { useState, useEffect } from "react";
import { Brain, BookOpen, Users, MessageCircle, Target, Zap, ArrowRight, Play, Check, Star, TrendingUp, Award, Clock, BarChart3 } from "lucide-react";

function App() {
  const [isVisible, setIsVisible] = useState(false);
  const [activeFeature, setActiveFeature] = useState(0);

  useEffect(() => {
    setIsVisible(true);
    const interval = setInterval(() => {
      setActiveFeature(prev => (prev + 1) % 4);
    }, 4000);
    return () => clearInterval(interval);
  }, []);

  const features = [
    { 
      icon: Brain, 
      title: "AI-Powered Curriculum", 
      desc: "Personalized learning paths generated by advanced AI algorithms",
      color: "from-blue-500 to-blue-600"
    },
    { 
      icon: Target, 
      title: "Goal-Based Learning", 
      desc: "Set personalized objectives and track progress with precision analytics",
      color: "from-sky-500 to-sky-600"
    },
    { 
      icon: MessageCircle, 
      title: "Intelligent Mentoring", 
      desc: "24/7 AI chatbot for instant doubt resolution and guidance",
      color: "from-blue-400 to-blue-500"
    },
    { 
      icon: TrendingUp, 
      title: "Smart Analytics", 
      desc: "Real-time insights and performance tracking for optimal learning",
      color: "from-sky-400 to-sky-500"
    }
  ];

  const stats = [
    { number: "15K+", label: "Active Learners", icon: Users },
    { number: "98%", label: "Success Rate", icon: Award },
    { number: "75K+", label: "AI Lessons", icon: BookOpen },
    { number: "24/7", label: "Smart Support", icon: Clock }
  ];

  const benefits = [
    "Personalized AI-driven curriculum",
    "Real-time progress tracking",
    "Interactive learning experience",
    "Expert instructor support"
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-yellow-50 via-blue-50 to-sky-50 relative">
      {/* Subtle Background Patterns */}
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute top-20 left-10 w-96 h-96 bg-yellow-200/20 rounded-full blur-3xl"></div>
        <div className="absolute top-60 right-20 w-80 h-80 bg-blue-200/30 rounded-full blur-3xl"></div>
        <div className="absolute bottom-32 left-1/2 w-72 h-72 bg-sky-200/25 rounded-full blur-3xl"></div>
      </div>

      
      <div className="relative z-10">
        <nav className="px-6 lg:px-8 py-6">
          <div className="max-w-7xl mx-auto flex justify-between items-center">
            <div className="flex items-center space-x-4">
              <div className="w-12 h-12 bg-gradient-to-r from-blue-500 to-sky-500 rounded-2xl flex items-center justify-center shadow-lg">
                <Brain className="w-7 h-7 text-white" />
              </div>
              <div>
                <h1 className="text-2xl font-bold text-slate-800">Edgenius</h1>
                <p className="text-xs text-slate-600 font-medium">AI Learning Platform</p>
              </div>
            </div>
            
            <div className="hidden md:flex items-center space-x-8">
              <a href="#features" className="text-slate-700 hover:text-blue-600 font-medium transition-colors">Features</a>
              <a href="#about" className="text-slate-700 hover:text-blue-600 font-medium transition-colors">About</a>
              <a href="#contact" className="text-slate-700 hover:text-blue-600 font-medium transition-colors">Contact</a>
            </div>
            
            <button className="px-6 py-2.5 bg-gradient-to-r from-blue-500 to-sky-500 text-white rounded-xl font-semibold hover:from-blue-600 hover:to-sky-600 transition-all duration-300 shadow-lg">
              Sign In
            </button>
          </div>
        </nav>

        {/* Hero Section */}
        <section className="px-6 lg:px-8 py-16">
          <div className="max-w-7xl mx-auto">
            <div className="grid lg:grid-cols-2 gap-16 items-center">
              {/* Left Content */}
              <div className={`space-y-8 transform transition-all duration-1000 ${isVisible ? 'translate-x-0 opacity-100' : '-translate-x-10 opacity-0'}`}>
                <div className="space-y-6">
                  <div className="inline-flex items-center space-x-2 px-4 py-2 bg-yellow-100 border border-yellow-200 rounded-full">
                    <Zap className="w-4 h-4 text-yellow-600" />
                    <span className="text-yellow-800 text-sm font-semibold">Production-Grade AI Platform</span>
                  </div>
                  
                  <h1 className="text-5xl lg:text-6xl font-black leading-tight text-slate-900">
                    The Future of
                    <span className="block bg-gradient-to-r from-blue-600 via-sky-500 to-blue-700 bg-clip-text text-transparent">
                      Personalized Learning
                    </span>
                  </h1>
                  
                  <p className="text-xl text-slate-700 leading-relaxed">
                    Transform your education journey with our AI-powered platform. Experience personalized curricula, 
                    intelligent assessments, and real-time mentoring designed for the modern learner.
                  </p>
                  
                  <div className="space-y-3">
                    {benefits.map((benefit, index) => (
                      <div key={index} className="flex items-center space-x-3">
                        <div className="w-6 h-6 bg-gradient-to-r from-blue-500 to-sky-500 rounded-full flex items-center justify-center">
                          <Check className="w-4 h-4 text-white" />
                        </div>
                        <span className="text-slate-700 font-medium">{benefit}</span>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="flex flex-col sm:flex-row gap-4 pt-4">
                  <button className="group px-8 py-4 bg-gradient-to-r from-blue-600 to-sky-600 text-white rounded-2xl font-semibold text-lg shadow-xl hover:shadow-2xl hover:from-blue-700 hover:to-sky-700 transition-all duration-300 transform hover:-translate-y-1">
                    <span className="flex items-center justify-center space-x-2">
                      <span>Start Learning Today</span>
                      <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                    </span>
                  </button>
                  <button className="group px-8 py-4 bg-white border-2 border-slate-200 text-slate-700 rounded-2xl font-semibold text-lg hover:border-blue-300 hover:bg-blue-50 transition-all duration-300">
                    <span className="flex items-center justify-center space-x-2">
                      <Play className="w-5 h-5" />
                      <span>Watch Demo</span>
                    </span>
                  </button>
                </div>
              </div>

              <div className={`transform transition-all duration-1000 delay-300 ${isVisible ? 'translate-x-0 opacity-100' : 'translate-x-10 opacity-0'}`}>
                <div className="relative">
                  <div className="bg-white rounded-3xl shadow-2xl border border-slate-200 p-8 relative overflow-hidden">
                    <div className="flex items-center justify-between mb-8">
                      <div>
                        <h3 className="text-2xl font-bold text-slate-800">Learning Dashboard</h3>
                        <p className="text-slate-600">Your personalized journey</p>
                      </div>
                      <div className="w-12 h-12 bg-gradient-to-r from-blue-500 to-sky-500 rounded-xl flex items-center justify-center">
                        {React.createElement(features[activeFeature].icon, { className: "w-6 h-6 text-white" })}
                      </div>
                    </div>
                    
                    <div className="space-y-6">
                      <div className={`p-6 rounded-2xl bg-gradient-to-r ${features[activeFeature].color} text-white`}>
                        <h4 className="text-xl font-bold mb-2">{features[activeFeature].title}</h4>
                        <p className="text-blue-100">{features[activeFeature].desc}</p>
                      </div>
                      
                      <div className="space-y-4">
                        <div className="flex justify-between items-center">
                          <span className="font-semibold text-slate-700">Overall Progress</span>
                          <span className="text-2xl font-bold text-blue-600">87%</span>
                        </div>
                        <div className="w-full bg-slate-200 rounded-full h-3">
                          <div className="bg-gradient-to-r from-blue-500 to-sky-500 h-3 rounded-full transition-all duration-1000" style={{width: '87%'}}></div>
                        </div>
                        
                        <div className="grid grid-cols-3 gap-4 pt-4">
                          <div className="bg-green-50 border border-green-200 rounded-xl p-4 text-center">
                            <Award className="w-6 h-6 text-green-600 mx-auto mb-2" />
                            <div className="text-sm font-semibold text-green-700">12 Completed</div>
                          </div>
                          <div className="bg-blue-50 border border-blue-200 rounded-xl p-4 text-center">
                            <BookOpen className="w-6 h-6 text-blue-600 mx-auto mb-2" />
                            <div className="text-sm font-semibold text-blue-700">3 In Progress</div>
                          </div>
                          <div className="bg-yellow-50 border border-yellow-200 rounded-xl p-4 text-center">
                            <Star className="w-6 h-6 text-yellow-600 mx-auto mb-2" />
                            <div className="text-sm font-semibold text-yellow-700">8 Mastered</div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="absolute -top-4 -right-4 bg-gradient-to-r from-yellow-400 to-yellow-500 rounded-2xl px-6 py-3 shadow-xl">
                    <div className="flex items-center space-x-2 text-white font-bold">
                      <BarChart3 className="w-4 h-4" />
                      <span className="text-sm">Live Analytics</span>
                    </div>
                  </div>

                  <div className="absolute -bottom-4 -left-4 bg-gradient-to-r from-sky-400 to-sky-500 rounded-2xl px-6 py-3 shadow-xl">
                    <div className="flex items-center space-x-2 text-white font-bold">
                      <MessageCircle className="w-4 h-4" />
                      <span className="text-sm">AI Assistant</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="px-6 lg:px-8 py-16 bg-white/50 backdrop-blur-sm">
          <div className="max-w-7xl mx-auto">
            <div className="grid grid-cols-2 lg:grid-cols-4 gap-8">
              {stats.map((stat, index) => (
                <div key={index} className="text-center group hover:transform hover:scale-105 transition-all duration-300">
                  <div className="w-16 h-16 bg-gradient-to-r from-blue-500 to-sky-500 rounded-2xl flex items-center justify-center mx-auto mb-4 group-hover:shadow-lg">
                    {React.createElement(stat.icon, { className: "w-8 h-8 text-white" })}
                  </div>
                  <div className="text-4xl font-black text-slate-800 mb-2">{stat.number}</div>
                  <div className="text-slate-600 font-semibold">{stat.label}</div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Footer */}
        <footer className="px-6 lg:px-8 py-12 bg-slate-50 border-t border-slate-200">
          <div className="max-w-7xl mx-auto text-center">
            <div className="flex flex-col lg:flex-row justify-between items-center space-y-4 lg:space-y-0">
              <div className="text-slate-600">
                <span className="font-semibold">Edgenius</span> • Production-Ready AI Learning Platform
              </div>
              <div className="flex items-center space-x-6 text-slate-500 text-sm">
                <span>Built with React • Node.js • FastAPI</span>
              </div>
            </div>
          </div>
        </footer>
      </div>
    </div>
  );
}

export default App;